#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 1:
        print common.get_err_msg(fname)
        sys.exit()

    # get executable
    exe = "emacs"

    # get path
    dot_latex_path = common.path_glue(common.manual_rep,
                                      "attach/latex_docs",
                                      "code.tex")
    # get command
    cmd = common.command(exe, dot_latex_path, "&")

    # execute command
    res = subprocess.call(cmd, shell=True)

    # show results
    common.show_results(res, fname)
