#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 1:
        print common.get_err_msg(fname)
        sys.exit()

    # get directory
    manual_dir = common.manual_rep

    # get command
    compile_cmd = common.command("make", "-C", manual_dir)

    # compile
    res = subprocess.call(compile_cmd, shell=True)
    if res != 0:
        print common.get_err_msg(fname)
        sys.exit()

    # print results
    print common.get_succ_msg(fname)
