#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common
from common import color


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) not in [2, 3]:
        print common.get_err_msg(fname)
        common.show_usage(fname, ["string"], ["number"])
        sys.exit()

    # get args
    string = "\"" + sys.argv[1] + "\""

    if len(sys.argv) == 3:
        index = sys.argv[2]
    else:
        index = "0"

    # print results
    if common.positive_null_integer(index) is True:
        index = int(index)

        # print preamble
        text = color.cyan + "\n" + "-" * 79
        print text

        # execute command
        cmd = common.command("grep", "-Rn", "-C", str(index), string)
        res = subprocess.call(cmd, shell=True)

        # print postamble
        text = color.cyan + "-" * 79
        print text
        print common.get_succ_msg(fname)

    else:
        text = color.green + "\n" + \
            color.pink + "  Results" + \
            color.green + ":" + "\n\n" + \
            color.green + " " * 4 + "Index " + \
            color.yellow + index + \
            color.green + " is invalid." + "\n"
        print text
        sys.exit()
