#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 1:
        print common.get_err_msg(fname)
        sys.exit()

    # get executable
    exe = "emacs"

    # get path
    path = common.path_glue(common.home,
                            ".emacs_dir/modes.lisp")

    # get command
    cmd = common.command(exe, path, "&")

    # execute command
    res = subprocess.call(cmd, shell=True)

    # show results
    common.show_results(res, fname)
