#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 1:
        print common.get_err_msg(fname)
        sys.exit()

    # get files
    tmp_file_list = os.listdir(common.script_dir)
    file_list = []
    for file_path in tmp_file_list:
        if "~" not in file_path[-1] \
           and "#" not in file_path \
           and common.extension(file_path) != "pyc":
            file_list.append(common.path_glue(common.script_dir, file_path))

    # get commands
    cmd_list = []
    for file_path in file_list:
        cmd = common.command("chmod", "744", file_path)
    cmd_list.append(cmd)

    # execute commands
    for cmd in cmd_list:
        res = subprocess.call(cmd, shell=True)
        if res != 0:
            print common.get_err_msg(fname)
            sys.exit()

    # show results
    print common.get_succ_msg(fname)
