#!/usr/bin/python


# imports
import os
import re
import subprocess
import sys

# custom imports
import common
from common import color


# main
if __name__ == "__main__":

    # get script name
    FNAME = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 3:
        print common.get_err_msg(FNAME)
        common.show_usage(FNAME, ["old_string", "new_string"], [])
        sys.exit()

    # get args
    OLD_STRING = sys.argv[1]
    NEW_STRING = sys.argv[2]

    # fix slashes
    OLD_STRING = OLD_STRING.replace("/", r"\/")
    NEW_STRING = NEW_STRING.replace("/", r"\/")

    # fix songle quotes
    OLD_STRING = OLD_STRING.replace("\"", r"\"")
    NEW_STRING = NEW_STRING.replace("\"", r"\"")

    # fix double quotes
    OLD_STRING = OLD_STRING.replace("\'", r"\'")
    NEW_STRING = NEW_STRING.replace("\'", r"\'")

    # execute command
    CMD = common.command("find", "./", "-type", "f", "-exec",
                         "sed", "-i",
                         "'s/" + OLD_STRING + "/" + NEW_STRING + "/g'",
                         "{}", r" \;")
    subprocess.call(CMD, shell=True, stdout=subprocess.PIPE)

    # show results
    print common.get_succ_msg(FNAME)
