
# target file base name
NAME = notes

# default action
all:
	rm -f $(NAME).pdf
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex
	rm -f $(NAME).aux $(NAME).log $(NAME).out $(NAME).toc *~
