;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(load "~/.emacs_dir/packages.el")
(load "~/.emacs_dir/settings.el")
(load "~/.emacs_dir/functions.el")
(load "~/.emacs_dir/shortcuts.el")
(load "~/.emacs_dir/modes.el")
(load "~/.emacs_dir/flycheck.el")
(load "~/.emacs_dir/indentation.el")

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(case-fold-search nil)
 '(inhibit-startup-screen t)
 '(package-selected-packages (quote (rust-mode phps-mode json-mode)))
 '(show-paren-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
