
(load "/home/apoka/.emacs_dir/packages.lisp")
(load "/home/apoka/.emacs_dir/settings.lisp")
(load "/home/apoka/.emacs_dir/functions.lisp")
(load "/home/apoka/.emacs_dir/shortcuts.lisp")
(load "/home/apoka/.emacs_dir/modes.lisp")
(load "/home/apoka/.emacs_dir/flycheck.lisp")
(load "/home/apoka/.emacs_dir/indentation.lisp")
