#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) not in [1, 2]:
        print common.get_err_msg(fname)
        sys.exit()

    # get args
    flag = None
    if len(sys.argv) == 2:
        flag = sys.argv[1]
        if common.alphanumeric(flag) is False:
            print common.get_err_msg(fname)
            sys.exit()

    # get path
    aux_path = common.path_glue("/tmp", "aux.txt")
    if flag is not None:
        aux_path = common.add_postfix(aux_path, "_" + flag)

    # get touch command
    touch_exe = "touch"
    touch_command = common.command(touch_exe, aux_path)

    # get emacs command
    emacs_exe = "emacs"
    emacs_command = common.command(emacs_exe, aux_path, "&")

    # execute commands
    res = subprocess.call(touch_command, shell=True)
    if res != 0:
        print common.get_err_msg(fname)
    res = subprocess.call(emacs_command, shell=True)
    if res != 0:
        print common.get_err_msg(fname)

    # show success message
    print common.get_succ_msg(fname)
