#!/usr/bin/python


# standard imports
import os
import sys

# custom imports
import common


# main
def main():

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 1:
        print common.get_err_msg(fname)
        sys.exit()

    # get commands
    backup = common.Backup()
    backup.do_backup()

    # show results
    print common.get_succ_msg(fname)


# main call
if __name__ == "__main__":

    main()
