#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 1:
        print common.get_err_msg(fname)
        sys.exit()

    # get paths
    trash_dir = common.path_glue(common.home, ".local/share/Trash")

    # get command
    cd_cmd = common.command("cd", trash_dir)
    rm_cmd = common.command("rm", "-f", "-r", "*")

    cmd = common.command(cd_cmd, ";", rm_cmd)

    # empty trash
    res = subprocess.call(cmd, shell=True)

    # show res
    common.show_results(res, fname)
