#!/usr/bin/python


# imports
import os
import subprocess
import sys

# custom imports
import common
from common import color


# main
if __name__ == "__main__":

    # get script name
    fname = os.path.realpath(__file__)

    # check args
    if len(sys.argv) != 2:
        print common.get_err_msg(fname)
        common.show_usage(fname, ["string"], [])
        sys.exit()

    # get args
    file_name = sys.argv[1]

    # get current dir
    current_dir = os.getcwd()

    # build command
    cmd = common.command("find", current_dir,
                         "-type", "d",
                         "-not", "-name", "\"*~\"",
                         "-not", "-name", "\"*#\"",
                         "-name", "\"*" + file_name + "\"*")

    # execute command
    sys.stdout.write(
        "\n" +
        color.yellow + ("-" * 2) +
        color.bblue + " DIRS " +
        color.yellow + ("-" * 11) +
        color.green + "\n")
    res = subprocess.call(cmd, shell=True)
    sys.stdout.write(
        color.yellow + ("-" * 19) +
        color.default + "\n\n")
